version: "3"
services:
  web:
    build: ./docker/
    working_dir: /app
    ports:
      - ${APP_HTTP_PORT}:3000
    volumes:
      - ./:/app
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
    stdin_open: true
    tty: true
